{% set name = "airbyte-api" %}
{% set version = "0.52.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/airbyte-api-{{ version }}.tar.gz
  sha256: 0abd4570083352cad9c23d1f6f59f288aeecca84d85746018d41de9c531aa852

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - certifi >=2023.7.22
    - charset-normalizer >=3.2.0
    - dataclasses-json >=0.6.4
    - idna >=3.4
    - jsonpath-python >=1.0.6
    - marshmallow >=3.19.0
    - mypy_extensions >=1.0.0
    - packaging >=23.1
    - python-dateutil >=2.8.2
    - requests >=2.31.0
    - six >=1.16.0
    - typing_inspect >=0.9.0
    - typing_extensions >=4.7.1
    - urllib3 >=1.26.18

test:
  imports:
    - airbyte_api
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/airbytehq/airbyte-api-python-sdk
  summary: Python Client SDK for Airbyte API
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/airbytehq/airbyte-api-python-sdk
  doc_url: https://github.com/airbytehq/airbyte-api-python-sdk/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
